# https://hub.docker.com/r/base/archlinux/
image: base/archlinux

before_script:
  - pacman -Syy python2 python2-pip --needed --noconfirm
  - pip2 install -r requirements_dev.txt

run_pylint:
  stage: test
  script: pylint tests.py
